name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root
    - name: Lint with flake8
      run: |
        poetry run flake8
    - name: Lint with black
      run: |
        poetry run black . --check
    - name: Lint with isort
      run: |
        poetry run isort -c .
    - name: Lint with mypy
      run: |
        poetry run mypy spacy_partial_tagger
    - name: Run tests
      run: |
        poetry run pytest --cov=spacy_partial_tagger --cov-report=term-missing
