name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -e ".[dev]"
    - name: Lint with ruff
      run: |
        ruff check spacy_partial_tagger
        ruff check tests
    - name: Lint with black
      run: |
        black . --check spacy_partial_tagger
        black . --check tests
    - name: Lint with mypy
      run: |
        mypy spacy_partial_tagger
        mypy tests
    - name: Run tests
      run: |
        pytest --cov=spacy_partial_tagger --cov-report=term-missing
